### ISSUE TITLE
If redis service is not running, exit with explicit error message

### ISSUE THREAD

**Issue by stevenweaver** [veg/datamonkey-js-server#56]
Currently, if the process cannot connect to a redis server, a cryptic message occurs. We should check for the redis service in server.js and report an error if no connection can be made.

**Comment by kjlevitz** [comment]
Example of error:
***ON START*** (Used: var client = redis.createClient(999, 999); within server.js file)

0|datamonk | Error: Redis connection to 192.168.0.255:6379 failed - connect ENETUNREACH 192.168.0.255:6379 - Local (0.0.0.0:0)
0|datamonk |     at RedisClient.on_error (/home/klevitz/datamonkey-js-server/node_modules/redis/index.js:196:24)
0|datamonk |     at Socket.<anonymous> (/home/klevitz/datamonkey-js-server/node_modules/redis/index.js:106:14)
0|datamonk |     at emitOne (events.js:96:13)
0|datamonk |     at Socket.emit (events.js:188:7)
0|datamonk |     at emitErrorNT (net.js:1290:8)
0|datamonk |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
0|datamonk |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
0|datamonk |     at Module.runMain (module.js:613:11)
0|datamonk |     at run (bootstrap_node.js:394:7)
0|datamonk |     at startup (bootstrap_node.js:160:9)
PM2        | App [datamonkey:7013] with id [0] and pid [24114], exited with code [1] via signal [SIGINT]
PM2        | Starting execution sequence in -fork mode- for app name:datamonkey:7013 id:0
PM2        | App name:datamonkey:7013 id:0 online
