### ISSUE TITLE
FADE jobs not working

### ISSUE THREAD

**Issue by stevenweaver** [veg/datamonkey-js-server#68]
It appears that there may be an issue with FADE. It is the only method in our stats page that hasn't had a completed job in over a week. 
![Screen Shot 2019-03-18 at 10 06 33](https://user-images.githubusercontent.com/535261/54535789-a9c07e00-4965-11e9-931a-79dde05112fc.png)

**Comment by stephenshank** [comment]
For what it's worth, upon reading this issue I was able to run this:
http://datamonkey.org/fade/5c8fa7d4b2d4ea6575106a45

I will keep an eye on the usage stats.
